### ISSUE TITLE
Practice Issue

### ISSUE THREAD

**Issue by tures23** [Openscapes/2023-swrcb#6]
paste here. @AHolder1

**Comment by AHolder1** [comment]
Got it! Thanks Tina! 😊

Sincerely,

Anna Holder | She, Her (What's this?<https://pronouns.org/>)
Environmental Scientist & Tribal Coordinator
Office of Information Management and Analysis (OIMA)
California State Water Resources Control Board
(916) 341-5096
***@***.******@***.***>
1001 I Street, 19th Floor
Sacramento, CA 95814

I respectfully acknowledge that I live and work on traditional, ancestral & unceded land of the Cayuse, Umatilla, Walla Walla<https://native-land.ca/maps/territories/cayuse-umatilla-and-walla-walla/> and Nisenan<https://native-land.ca/maps/territories/nisenan/> nations. Whose land are you on?<https://native-land.ca/>

CONFIDENTIALITY NOTICE: This Communication, with its contents, may contain confidential and/or legally privileged information. It is solely for the use of the intended recipient(s). Unauthorized interception, review, use or disclosure is prohibited and may violate applicable laws, including the Electronic Communications Privacy Act. If you are not the intended recipient, please contact the sender and destroy all copies of the communication.

From: tures23 ***@***.***>
Sent: Monday, September 18, 2023 2:49 PM
To: Openscapes/2023-swrcb ***@***.***>
Cc: Holder, ***@***.*** ***@***.***>; Mention ***@***.***>
Subject: [Openscapes/2023-swrcb] Practice Issue (Issue #6)

EXTERNAL:


paste here. @AHolder1<https://github.com/AHolder1>

**Comment by AHolder1** [comment]
Test numero 2

**Comment by tures23** [comment]
complete :)
